### ISSUE TITLE
Timesheets MealbreakSlots now is array

### ISSUE THREAD

**Issue by sergiogmuro** [communityds/deputy-api-wrapper#16] opened 2022-12-08 20:00 UTC
Hi, I have a problem with timesheets, now MealbreakSlots are in array format. Please can you check that?
![image](https://user-images.githubusercontent.com/22686048/206556007-622b45b0-a46f-4fec-a507-6c30b95e3bf2.png)

Thanks

**Comment by joni2back** [comment] 2022-12-08 20:05
Same issue here, seems sometimes is an array, others is scalar

![image](https://user-images.githubusercontent.com/2049935/206556914-a8c7c2c0-944a-4d2a-8a3c-216013aad282.png)


@simonp7n @SonOfHarris

**Comment by joni2back** [comment] 2022-12-08 20:57
Already fixed by extending this config

```[
            'auth' => [
                'class' => 'CommunityDS\Deputy\Api\Adapter\Config\PermanentToken',
                'token' => env('DEPUTY_API_TOKEN'),
            ],
            'target' => [
                'class' => 'CommunityDS\Deputy\Api\Adapter\Config\TargetConfig',
                'domain' => env('DEPUTY_API_DOMAIN'),
            ],
            'schema' => [
                'class' => 'CommunityDS\Deputy\Api\Schema\Registry',
                'resources' => [
                    "Timesheet" => [
                        "modelClass" => "CommunityDS\Deputy\Api\Model\Timesheet",
                        "fields" => [
                            "Slots" => "Array",
                            "StartTime" => "UnixTimestamp",
                            "EndTime" => "UnixTimestamp",

                            "MealBreakSlots" => "Array",
                        ]
                    ]
                ],
            ],
        ]```

**Comment by SonOfHarris** [comment] 2022-12-08 23:01
Thanks for letting us know. According to the Deputy API documentation the slots should be String: https://developer.deputy.com/deputy-docs/docs/timesheet

I'm aware that when creating a timesheet via the UI that there's the option of logging multiple breaks. So this may have been caused by that change and Deputy likely hasn't updated the API as a result.

Is there any pattern of behaviour that you've observed that makes it a String or an Array?

I might reach out to Deputy to see if they could provide some insight.

Once there's a better idea on what the expected type is there could be some kind of translation to ensure it remains consistent.

**Comment by SonOfHarris** [comment] 2022-12-13 23:34
After some discussions with Deputy it does appear that the `MealbreakSlots` property can be both an empty string `""` and an array.

The `MealbreakSlots` is a log of when someone physically clocks out and back in from a break. This could explain why some Timesheet records have this issue and others don't.

The wrapper will consider the `MealbreakSlots` to be an Array from here on out. If an empty string is returned then the wrapper will consider that to be an empty array. If a non-empty string is returned it will be converted to an array where the string is the first item.

At this point in time, CDS doesn't use this property so there isn't a need on our side to provide a better data structure for the items within the MealbreakSlots array. If there's a requirement from your side please let me know. If there is, providing a helper method rather than directly accessing the `MealbreakSlots` property might be a better solution.

**Closed as completed** 2022-12-16 03:48 UTC
Labels: bug
